version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASS@db:$DB_PORT/$DB_NAME
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
